### ISSUE TITLE
Stop slow tests after a set timeout period, instead of skipping them

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#195]
## Overview

As made evident by #191, skipping slow tests potentially hides bugs. These test should instead be stopped after a set period of time, e.g. ~15s, to ensure they don't cause errors.

## Expected Behavior

The identification tests should fail on travis even when `RUN_SLOW_TESTS` isn't set to `true`.

## Technical details

The desired behavior should be able to be accomplished by combining the [pytest-timeout](https://pypi.python.org/pypi/pytest-timeout#usage) package with the [`pytest.mark.xfail` raises-parameter](https://docs.pytest.org/en/latest/skipping.html#raises-parameter). Setting the environment variable `RUN_SLOW_TESTS=true` should cause the timeout parameters to be ignored.

## Acceptance criteria

 - [ ] Running on travis with `RUN_SLOW_TESTS=false` (the default) should show the `src/tests/test_endpoints.py::test_identify` function as failed. 
 - [ ] Running on travis with `RUN_SLOW_TESTS=false` (the default) should show the `src/tests/test_segmentation.py::test_lung_segmentation` function as passed. 
 - [ ] Running on travis with `RUN_SLOW_TESTS=true` should show the cause travis to timeout the build. 

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by WGierke** [comment]
`The identification tests should fail on travis even when RUN_SLOW_TESTS isn't set to true.`
Assuming that an error occurs in the seconds before the timeout, right? Otherwise the test passes because the timeout is not seen as an error?

**Comment by reubano** [comment]
@WGierke yes, exactly.

**Comment by WGierke** [comment]
If I understand [this](https://stackoverflow.com/questions/46766899/pytest-timeout-fail-test-instead-killing-whole-test-run) correctly, it doesn't appear to be so easy to catch the case when pytest-timeout stops a method because the SIGALRM signal does not produce an exception. I was able to implement the remaining logic but currently I'm struggling with somehow catching that timeout exception:
`git checkout bcb743766386794bf373bd14972cb3b05c60d727`  
`git apply patch.txt`
[patch.txt](https://github.com/concept-to-clinic/concept-to-clinic/files/1485956/patch.txt)
Does someone have an idea how to still let tests pass even when they timeout?

**Comment by WGierke** [comment]
Nvm, I think I got it :)
