### ISSUE TITLE
Any reason for having HyperlinkedModelSerializer instead of ModelSerializer?

### ISSUE THREAD

**Issue by Serhiy-Shekhovtsov** [concept-to-clinic/concept-to-clinic#228]
Is there any reason for using `HyperlinkedModelSerializer` for serializing the data before sending it to client side?

### Having this serializer have following drawbacks:

- Returned data doesn't have the **id**. Here is an example of data for `/api/candidates.json` method:
`{"url":"http://interface:8001/api/candidates/1.json","centroid":{ ... },"created":" ... ","probability_concerning":0.3,"case":"http://interface:8001/api/cases/1.json"}`
- Returned URL is not usable. 
  - As you can see, it's absolute and since the port doesn't match the Vue.js server's port - AJAX requests to that URL are blocked by the browser.
  - Also the url contains **.json** extension. For example, services we have for marking/dismissing candidates look like this: `candidates/1/mark`, `candidates/1/dismiss`

### So, what are the benefits?
Maybe I am missing something here, since I am totally new to django, but it looks like replacing `HyperlinkedModelSerializer` with `ModelSerializer` helps to solve the issue of missing **id** and it also doesn't return unusable urls.

## Possible Solution
AFAIK, we can still use `HyperlinkedModelSerializer` but patch it by overriding a method for creating serializer and passing `None` as `request`. Or we can simply use to `ModelSerializer`.

**Comment by isms** [comment]
Hyperlinked fields let the frontend get canonical URLs from the backend rather than doing `domain + id + endpoint` stuff in frontend JS which will immediately break if the endpoints change or if a field other than `id` is used for lookups in the future. Instead the idea is that you can fetch a related resource by fetching `object.url`. You can make it work either way but including links seems to be considered truer to the REST concept.

Two address the two specifics:

1. "Also the url contains .json extension" - is there an example of an issue? Or is this a setting that can simply be changed on the serializer or view? Seems like views are still free to return custom endpoints like `/mark` and `/dismiss` that don't go by this scheme as the only thing HyperlinkedModelSerializer tries to add links for is the specific instance it is serializing.

2. Looks like we may be able to get relative URLs simply by having the `[Thing]ViewSet` views in `backend/api/views.py` all extend a class which extends the `viewsets.ModelViewSet`'s [get_serializer_context](http://www.cdrf.co/3.1/rest_framework.viewsets/ModelViewSet.html#get_serializer_context) and overriding the parent context making sure `request=None` (ref: https://github.com/encode/django-rest-framework/issues/3532#issuecomment-223301559)

Is there are strong reason to prefer reverting to non-hyperlinked versions?

**Comment by Serhiy-Shekhovtsov** [comment]
@isms, your suggestion to inherit all from base and override the `get_serializer_context` is nice, didn't think about it. And after I have implemented it the issue with `.json` is also gone.

Btw, here are my findings about `.json` issue: When request is *not* set to None for the serializer, then generated URL will be absolute **and also** copy the extension of the query. If you load `/api/candidates.json` each candidate will have URL `xxx/api/candidates/1.json`.

**Comment by isms** [comment]
Closed by #231 - thanks @Serhiy-Shekhovtsov.
