### ISSUE TITLE
Create a smaller test image dataset

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#38]
## Overview

Currently test images are stored in the [git repository](https://github.com/concept-to-clinic/concept-to-clinic/tree/master/tests/assets). These images are formatted as directories of [DICOM](https://en.wikipedia.org/wiki/DICOM) files. Each directory contains hundreds of files, and consumes ~100MB of space. We would like to reduce the number of files to the bare minimum needed to detect nodules and pass the tests.

## Expected Behavior

The number of DICOM directories and images is reduced to the minimum amount necessary (1 - 3 directories, each with 5 - 10 DICOM files).

## Technical details

 - Each directory contains an xml file with metadata about the included DICOM files. You may need to edit this file. 

## Acceptance criteria

 - [ ] number of test images is reduced as described above
 - [ ] the tests suite passes with the reduced image dataset

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by tdraebing** [comment]
I had a look into this and found that the dimensions metadata is in the metadata of each *.dcm-file. The xml-file denotes the position of the marked nodules and is not needed to load the images. 
`pydicom` actually does not care if you delete images of a series, but `dicom-numpy` does, since it tests, whether the distance between slices is the same. Since the numbering of the files is not in the same order as the z-position of the slice, simply deleting files does not work here.
I wrote a function that can reduce the dimensions of a series in x, y and z. I think that this function may be useful in general, because new test image sets might be needed for different tasks. I will create smaller test sets asap and create a pull request. Should I include the script as well in this pull request?
What should happen to the full data sets? I would propose to change the docker script to only include the small dataset, when running the server, but keep the original files in the repo.

**Comment by reubano** [comment]
Yes, you can include the script. Also, feel free to remove the original files from the repo. The goal of the PR is to reduce the repo's total size.

**Comment by tdraebing** [comment]
I finally finished the pull request.
But I have some concerns that I wanted to share before the pull request is merged. While the reduced size of the dataset is no issue for testing tooling or similar tasks, it might reduce the dataset's information content considerably, which might cause issues for training models etc. A lot of positional information gets lost for example: Where in the lung is the nodule/tumor? Also the nodules annotated in the *.xml-files are pretty wide spread, so we lost a few here.
In the current pull request the *.xml-files, which could be useful for supervised learning, are not included. If you think they should be included I will happily update them to the new test set and add them in a new commit. I would also suggest to create a new issue that deals with reading the xml-data into memory.

Please let me now what you think.

Cheers,
Thomas

**Comment by reubano** [comment]
I don't think we will have to worry about training too much since anyone serious about that will likely dl the entire data set. This is mainly to lower the bar for someone wanting to clone the repo and play around. Fortunately, now that #17 is closed, contributors still have access to the full size test data set if they want it. 

The main question now is how best to integrate these two. Maybe sub-folders under `assets`, e.g., `assets/full` and `assets/partial`?

**Comment by tdraebing** [comment]
That seems like a good idea. I will update the pull request to change the doc-string styling and include both test set sizes. I think it will also make sense to add a short readme-file to the assets folder giving the specifics for anyone, who wants to fiddle around with the test data.
