### ISSUE TITLE
External links in https://concepttoclinic.drivendata.org/documentation do not work

### ISSUE THREAD

**Issue by alexanderrich** [concept-to-clinic/concept-to-clinic#54]
## Expected Behavior
When viewing the documentation through https://concepttoclinic.drivendata.org/documentation, external links should take the browser to a new webpage.

## Current Behavior
Clicking external links (at least in Firefox and Chrome) leads to a page with the "Concept to Clinic" heading that is otherwise blank.

## Possible Solution
It looks like the documentation page uses an iframe to display a readthedocs page. I think this iframe might need to be reconfigured to allow redirecting the target of its parent window. Since concepttoclinic.drivendata.org isn't controlled by this public github repo, I think an admin will have to fix this.

## Steps to Reproduce
1. Open https://concepttoclinic.drivendata.org/documentation
2. Go to "Getting Started"
3. Click the "submitting a PR to the GitHub repository" link.
4. The screen goes blank.

**Comment by WGierke** [comment]
Hey @alexanderrich 
the reason is that external pages (such as https://github.com/concept-to-clinic/concept-to-clinic in your example) set the [Content-Security-Policy frame-ancestors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) no `none`, meaning that no third party is allowed to frame their content.
Since we can't alter their CSP flags, the only solution from my POV is to open all links in our documentation that refer to such pages in a new tab using `target="_blank"` for every link tag.

**Comment by isms** [comment]
@WGierke We can alter CSP flags if necessary. Any recommendations?

**Comment by WGierke** [comment]
@isms but we can't alter them of third parties such as Github. If they set frame-ancestors to none, it's not possible to frame their content at all. So I'll agree with @alexanderrich that either opening the problematic links in a new tab using `target="_blank"` or to directly link to the readthedocs page instead of including it in an iframe are the only reasonable solutions here (from my point of view).

**Comment by lamby** [comment]
On the ``target="_blank"`` thing — I was looking at the Sphinx source code  earlier for a configuration option and it looks like it should be doing this already, so not sure what's up. Sphinx is setting the ``external`` class, however, so we could add some Javascript to either hijack clicks to those, or simply to add the ``target="_blank"`` on page load.

Re. altering the CSP flags, I fear that:
a) it would mean essentially disabling their protection entirely as we would need to allow any link.
b) We don't want to do this anyway as it traps the user on, say, GitHub.com within our ``iframe`` which is a little nasty.

I'm really rather tempted to drop the ``iframe`` - amongst their IA/UX issues (where is my copy-pastable canonical link!), they are an accessibility nightmare...

@WGierke What do you think? :)

**Comment by WGierke** [comment]
I'd completely agree with dropping the iframe in favor of e.g. opening the documentation page in a new tab. This way, the user stays on  https://concepttoclinic.drivendata.org while he enjoys expected browsing behavior in the documentation and by following all external links.

**Comment by reubano** [comment]
Tagging this as official

**Comment by lamby** [comment]
Thanks @WGierke !

**Comment by lamby** [comment]
@WGierke This should be fixed now. Awarded points for the research etc.  Thank you again.
