### ISSUE TITLE
React for the frontend instead of Vue.js

### ISSUE THREAD

**Issue by yazan-alomari** [concept-to-clinic/concept-to-clinic#75]
## Expected Behavior
React component-based approach for the frontend is better than using a template-based syntax.

## Current Behavior
HTML-based template syntax

## Possible Solution
Reusable components by react, especially the treeview folder structure and the image with its metadata for the selected case. React components are easy to implement and can interface with any backed api regardless of the framework used.

## Steps to Reproduce
Frontend code written till now is very minimal. We can start writing a React mock up and feed the components dummy data.

**Comment by isms** [comment]
Hi @yazan-alomari, thanks for contributing :+1: 

> Reusable components by react, especially the treeview folder structure and the image with its metadata for the selected case.
In general we're not excited to have Framework X versus Framework Y debates, but to at least address what seems to be the point about reusable components: please see [this page on reusable Vue components](https://vuejs.org/v2/guide/components.html) and then let us know if you still think this issue is a pertinent Vue vs. React consideration.

Closing this issue at the moment as non-actionable but happy to respond to comments here if other points need to be considered.
